SENDING_INTERVAL_MIN = 0.0001
WORDS_CACHE_REFRESH_INTERVAL_H = 2
SHOW_NOTIFICATION_TIME_SEC = 20
DAEMON_MAIN_LOOP_SLEEP_TIME_SEC = SENDING_INTERVAL_MIN / (60.0 * 2)

DICTIONARY_ICON_PATH = "resources/dictionary-icon.png"

WORDS_DICTIONARY_PATH = "tests/test_data/input_tree_row_valid.txt"
